apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cm-demo
  labels:
    app: cm-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cm-demo
  template:
    metadata:
      labels:
        app: cm-demo
    spec:
      containers:
        - name: cm-demo
          image: docker-repo.sk-devops.com/docker-sk-repo/sk:25
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: dev-cm
